import type { NextApiRequest, NextApiResponse } from "next";
import { collection, addDoc, Timestamp } from "firebase/firestore";
import { db } from "../../../lib/firebase";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    const dummyBookings = [
        {
          requestId: "REQ-001",
          touristId: "TOURIST-001",
          touristName: "John Doe",
          guideId: "GUIDE-001",
          guideName: "Suresh Silva",
          title: "Kandy Temple Tour",
          destination: "Kandy",
          startDate: "2025-01-12",
          endDate: "2025-01-13",
          status: "pending",
          agreedPrice: 20000,
          numberOfPeople: 2,
          budget: 25000,
          tourType: "Cultural",
        },
        {
          requestId: "REQ-002",
          touristId: "TOURIST-002",
          touristName: "Emily Rose",
          guideId: "GUIDE-002",
          guideName: "Kasun Perera",
          title: "Ella Hiking Escape",
          destination: "Ella",
          startDate: "2025-02-05",
          endDate: "2025-02-06",
          status: "upcoming",
          agreedPrice: 35000,
          numberOfPeople: 3,
          budget: 40000,
          tourType: "Adventure",
        },
        {
          requestId: "REQ-003",
          touristId: "TOURIST-003",
          touristName: "Robert Chang",
          guideId: "GUIDE-003",
          guideName: "Nimal Jayasuriya",
          title: "Galle Fort Walking Tour",
          destination: "Galle",
          startDate: "2025-03-10",
          endDate: "2025-03-10",
          status: "completed",
          agreedPrice: 15000,
          numberOfPeople: 1,
          budget: 20000,
          tourType: "City Tour",
        },
        {
          requestId: "REQ-004",
          touristId: "TOURIST-004",
          touristName: "Sophia Lee",
          guideId: "GUIDE-001",
          guideName: "Suresh Silva",
          title: "Sigiriya Rock Visit",
          destination: "Sigiriya",
          startDate: "2025-01-25",
          endDate: "2025-01-25",
          status: "cancelled",
          agreedPrice: 28000,
          numberOfPeople: 2,
          budget: 30000,
          tourType: "Heritage",
        },
        {
          requestId: "REQ-005",
          touristId: "TOURIST-005",
          touristName: "Liam Johnson",
          guideId: "GUIDE-004",
          guideName: "Mahinda Kumara",
          title: "Nuwara Eliya Tea Tour",
          destination: "Nuwara Eliya",
          startDate: "2025-02-15",
          endDate: "2025-02-16",
          status: "pending",
          agreedPrice: 32000,
          numberOfPeople: 4,
          budget: 45000,
          tourType: "Nature",
        },
        {
          requestId: "REQ-006",
          touristId: "TOURIST-006",
          touristName: "Ava Martinez",
          guideId: "GUIDE-005",
          guideName: "Ruwan Fernando",
          title: "Colombo City Highlights",
          destination: "Colombo",
          startDate: "2025-03-01",
          endDate: "2025-03-01",
          status: "upcoming",
          agreedPrice: 12000,
          numberOfPeople: 2,
          budget: 15000,
          tourType: "City Tour",
        },
        {
          requestId: "REQ-007",
          touristId: "TOURIST-007",
          touristName: "Noah Kim",
          guideId: "GUIDE-006",
          guideName: "Janaka Rathnayake",
          title: "Trincomalee Beach Visit",
          destination: "Trincomalee",
          startDate: "2025-04-05",
          endDate: "2025-04-06",
          status: "completed",
          agreedPrice: 45000,
          numberOfPeople: 3,
          budget: 50000,
          tourType: "Beach",
        },
        {
          requestId: "REQ-008",
          touristId: "TOURIST-008",
          touristName: "Olivia Brown",
          guideId: "GUIDE-002",
          guideName: "Kasun Perera",
          title: "Adam's Peak Hike",
          destination: "Nallathanniya",
          startDate: "2025-04-18",
          endDate: "2025-04-19",
          status: "pending",
          agreedPrice: 38000,
          numberOfPeople: 2,
          budget: 42000,
          tourType: "Adventure",
        },
        {
          requestId: "REQ-009",
          touristId: "TOURIST-009",
          touristName: "Ella Thompson",
          guideId: "GUIDE-007",
          guideName: "Chathura Alwis",
          title: "Polonnaruwa Ancient Ruins",
          destination: "Polonnaruwa",
          startDate: "2025-02-20",
          endDate: "2025-02-20",
          status: "cancelled",
          agreedPrice: 18000,
          numberOfPeople: 1,
          budget: 20000,
          tourType: "History",
        },
        {
          requestId: "REQ-010",
          touristId: "TOURIST-010",
          touristName: "James Wilson",
          guideId: "GUIDE-003",
          guideName: "Nimal Jayasuriya",
          title: "Bentota Water Sports",
          destination: "Bentota",
          startDate: "2025-05-12",
          endDate: "2025-05-12",
          status: "upcoming",
          agreedPrice: 55000,
          numberOfPeople: 5,
          budget: 60000,
          tourType: "Adventure",
        },
        {
          requestId: "REQ-011",
          touristId: "TOURIST-011",
          touristName: "Mia Park",
          guideId: "GUIDE-004",
          guideName: "Mahinda Kumara",
          title: "Jaffna Cultural Tour",
          destination: "Jaffna",
          startDate: "2025-03-28",
          endDate: "2025-03-29",
          status: "completed",
          agreedPrice: 38000,
          numberOfPeople: 2,
          budget: 45000,
          tourType: "Cultural",
        },
        {
          requestId: "REQ-012",
          touristId: "TOURIST-012",
          touristName: "Lucas White",
          guideId: "GUIDE-008",
          guideName: "Sanjaya Weerakkody",
          title: "Mirissa Whale Watching",
          destination: "Mirissa",
          startDate: "2025-04-02",
          endDate: "2025-04-02",
          status: "pending",
          agreedPrice: 30000,
          numberOfPeople: 3,
          budget: 35000,
          tourType: "Nature",
        },
        {
          requestId: "REQ-013",
          touristId: "TOURIST-013",
          touristName: "Harper Davis",
          guideId: "GUIDE-009",
          guideName: "Anuradha Silva",
          title: "Anuradhapura Heritage Walk",
          destination: "Anuradhapura",
          startDate: "2025-02-10",
          endDate: "2025-02-10",
          status: "completed",
          agreedPrice: 17000,
          numberOfPeople: 1,
          budget: 20000,
          tourType: "History",
        },
        {
          requestId: "REQ-014",
          touristId: "TOURIST-014",
          touristName: "Charlotte Young",
          guideId: "GUIDE-010",
          guideName: "Rasika Dissanayake",
          title: "Negombo Lagoon Boat Tour",
          destination: "Negombo",
          startDate: "2025-01-10",
          endDate: "2025-01-10",
          status: "pending",
          agreedPrice: 14000,
          numberOfPeople: 2,
          budget: 18000,
          tourType: "Nature",
        },
        {
          requestId: "REQ-015",
          touristId: "TOURIST-015",
          touristName: "Amelia Scott",
          guideId: "GUIDE-006",
          guideName: "Janaka Rathnayake",
          title: "Arugam Bay Surf Trip",
          destination: "Arugam Bay",
          startDate: "2025-05-20",
          endDate: "2025-05-22",
          status: "upcoming",
          agreedPrice: 65000,
          numberOfPeople: 4,
          budget: 70000,
          tourType: "Beach",
        },
      ];      

    for (const booking of dummyBookings) {
      await addDoc(collection(db, "bookings"), booking);
    }

    return res.status(200).json({
      success: true,
      message: "Dummy bookings inserted successfully",
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      error: error.message,
    });
  }
}
